### ISSUE TITLE
Merge into bs-webapi-incubator

### ISSUE THREAD

**Issue by glennsl** [Jimexist/bs-history#1]
Wouldn't it be better to improve the [existing bindings](https://github.com/BuckleTypes/bs-webapi-incubator/tree/master/src/dom/html) in bs-web-incubator, and keep all the HTML APIs together in one place?

**Comment by jimexist** [comment]
@glennsl this was meant to be a bindings for history library, which is another abstraction above the HTML history API to allow its usage in non-dom environment as well.

**Comment by glennsl** [comment]
Oh, sorry, nevermind then! I was collecting bindings for the index, so didn't look all that closely.
